//src/app/assets/i18n/en-UK.json.ts
export const enUK = {
  hello: "Hello",
  world: "World",
  welcome: "Welcome to the world of i18n!",
  goodbye: "Goodbye",
  goodbye_message: "Goodbye, then see you!",
  search: "Intermediate",
  search_placeholder: "Search for something ...",
  search_button: "Intermediate",
  search_results: "Search results",
  search_no_results: "Search results not found",
  search_result: "Search result",
  search_result_count: "Number of Search Results",
  search_result_count_plural: "Number of Search Results",
  search_result_count_0: "No search results",
  computer: "Computer",
  internet: "Internet",
  language: "Language",
  book: "Book",
  school: "School",
  teacher: "Teacher",
  student: "Student",
  university: "University",
  science: "Science",
  technology: "Technology",
  engineering: "Engineering",
  mathematics: "Maths",
  medicine: "Medicine",
  hospital: "Hospital",
  doctor: "Doctor",
  nurse: "Nurse",
  health: "Health",
  exercise: "Exercise",
  sport: "Sport",
  football: "Football",
  basketball: "Basketball",
  tennis: "Tennis",
  music: "Music",
  movie: "Film",
  cinema: "Cinema",
  actor: "Actor",
  actress: "Actress",
  director: "Director",
  writer: "Writer",
  novel: "Novel",
  story: "Story",
  news: "News",
  journalism: "Journalism",
  camera: "Camera",
  photography: "Photography",
  painting: "Picture",
  art: "Art",
  sculpture: "Statue",
  architecture: "Architectural",
  city: "City",
  country: "Country",
  village: "Bay",
  ocean: "Ocean",
  river: "River",
  mountain: "Mountain",
  forest: "Forest",
  tree: "Tree",
  flower: "Flower",
  animal: "Animal",
  bird: "Bird",
  fish: "Fish",
  dog: "Dog",
  cat: "Cat",
  car: "Car",
  bicycle: "Bicycle",
  train: "Train",
  airplane: "Aeroplane",
  travel: "Trip",
  hotel: "Hotel",
  restaurant: "Restaurant",
  food: "Food",
  water: "This",
  coffee: "Coffee",
  tea: "Tea",
  bread: "Bread",
  butter: "Butter",
  cheese: "Cheese",
  sugar: "Sugar",
  salt: "Salt",
  pepper: "Pepper",
  fruit: "Fruit",
  apple: "Apple",
  banana: "Banana",
  orange: "Orange",
  grape: "Grape",
  cherry: "Cherry",
  strawberry: "Strawberry",
  lemon: "Lemon",
  vegetable: "Vegetable",
  tomato: "Tomatoes",
  potato: "Potatoes",
  onion: "Onion",
  garlic: "Garlic",
  carrot: "Carrot",
  cucumber: "Cucumber",
  money: "Money",
  bank: "Bank",
  market: "Sunday",
  shop: "Shopping centre",
  store: "Shop",
  price: "Price",
  discount: "Discount",
  sale: "Sales",
  business: "Work",
  company: "Company",
  boss: "Boss",
  manager: "Executive",
  employee: "Worker",
  meeting: "Meeting",
  project: "Project",
  contract: "Agreement",
  agreement: "Agreement",
  law: "Law",
  judge: "Judge",
  lawyer: "Lawyer",
  court: "Court",
  government: "Government",
  politics: "Politics",
  election: "Vote",
  vote: "Vote",
  citizen: "Citizen",
  education: "Education",
  teaching: "Teaching",
  learning: "Learning",
  knowledge: "Information",
  wisdom: "Wisdom",
  understanding: "Understanding",
  college: "College",
  professor: "Professor",
  lecture: "Lesson",
  classroom: "Class",
  homework: "Homework",
  assignment: "Duty",
  exam: "Exam",
  test: "Test",
  grade: "Notes",
  subject: "Course subject",
  physics: "Physical",
  chemistry: "Chemical",
  biology: "Biology",
  history: "History",
  geography: "Geography",
  literature: "Literature",
  reading: "Reading",
  writing: "Don't write",
  speaking: "Speech",
  listening: "Listening",
  presentation: "Presentation",
  discussion: "Argument",
  debate: "Discussion",
  notebook: "Notebook",
  textbook: "Textbook",
  library: "Library",
  research: "Research",
  experiment: "Experiment",
  laboratory: "Lab",
  curriculum: "Curriculum",
  syllabus: "Course program",
  lesson: "Lesson",
  educator: "Instructor",
  principal: "Manager",
  dean: "Dean",
  diploma: "Diploma",
  degree: "Degree",
  scholarship: "Scholarship",
  tuition: "Tuition fee",
  academic: "Academic",
  graduate: "Graduate",
  postgraduate: "Graduate",
  undergraduate: "Licence",
  certificate: "Certificate",
  enrollment: "Record",
  attendance: "Continue",
  mentor: "Directory",
  tutor: "Tutor",
  coaching: "Coaching",
  instruction: "Instructions",
  self_study: "Self _work",
  group_study: "Group work",
  online_learning: "Learning online",
  distance_learning: "Distance Learning",
  e_learning: "E_learning",
  virtual_classroom: "Virtual class",
  interactive_learning: "Interactive learning",
  critical_thinking: "Critical thinking",
  problem_solving: "Solving problem",
  collaboration: "Partnership",
  communication: "Communication",
  creativity: "Creativity",
  innovation: "Innovation",
  motivation: "Motivation",
  inspiration: "Inspiration",
  discipline: "Discipline",
  time_management: "Time management",
  goal_setting: "Targeting",
  achievement: "Success",
  evaluation: "Evaluation",
  feedback: "Feedback",
  revision: "Review",
  memorization: "Memorizing",
  analysis: "Analysis",
  synthesis: "Synthetic",
  comprehension: "Clutch",
  interpretation: "Interpretation",
  website: "Website",
  homepage: "Home page",
  about: "About",
  contact: "Communication",
  services: "Services",
  products: "Products",
  portfolio: "Portfolio",
  blog: "Blog",
  faq: "FAQ",
  support: "Support",
  privacy_policy: "Privacy Policy",
  terms_of_service: "Service Terms",
  login: "Entrance",
  signup: "Register",
  logout: "Make out",
  profile: "Profile",
  dashboard: "Control Panel",
  settings: "Settings",
  notifications: "Notifications",
  filter: "Filter",
  sort: "Ranking",
  category: "Category",
  subscribe: "Subscribe",
  newsletter: "Bulletin",
  download: "Download",
  upload: "Install",
  share: "Share",
  like: "Like",
  comment: "Comment",
  review: "Examination",
  rating: "Point",
  terms: "Conditions",
  conditions: "Conditions",
  security: "Security",
  cookies: "Cookies",
  advertisement: "Advert",
  sitemap: "Site Map",
  help: "Help",
  forum: "Forum",
  community: "Community",
  members: "Members",
  admin: "Executive",
  moderator: "Moderator",
  user: "User",
  visitor: "Visitor",
  profile_picture: "Profile picture",
  banner: "Banner",
  header: "Upper information",
  footer: "Sub _information",
  menu: "Menu",
  navigation: "Strolling",
  button: "Button",
  link: "Connection",
  icon: "Symbol",
  image: "Visual",
  video: "Video",
  audio: "Sound",
  gallery: "Gallery",
  media: "Media",
  theme: "Theme",
  template: "Template",
  layout: "Order",
  design: "Design",
  content: "Contents",
  text: "Text",
  font: "Font",
  color: "Colour",
  background: "Background",
  animation: "Animation",
  effect: "Effect",
  plugin: "Plug _in",
  extension: "Extension",
  database: "Database",
  server: "Presenter",
  hosting: "Hosting",
  domain: "Domain name",
  seo: "SEO",
  analytics: "Analysis",
  performance: "Performance",
  optimization: "Optimization",
  traffic: "Traffic",
  conversion: "Transformation",
  advertising: "Advertising",
  social_media: "Social media",
  campaign: "Offer",
  ecommerce: "E_commerce",
  cart: "Basket",
  checkout: "Payment",
  payment: "Payment",
  invoice: "Invoice",
  subscription: "Subscription",
  membership: "Membership",
  donation: "Donation",
  customer: "Customer",
  client: "Customer",
  order: "Order",
  tracking: "Follow_up",
  delivery: "Delivery",
  support_ticket: "Support ticket",
  udemy: "Udemy",
  course: "Course",
  module: "Module",
  section: "Section",
  instructor: "Instructor",
  enroll: "Signature",
  completion: "Completion",
  quiz: "Test",
  transcript: "Transcript",
  subtitles: "Subtitles",
  notification: "Notification",
  bookmark: "Location bookmark",
  wishlist: "Request list",
  popular: "Popular",
  trending: "Trend",
  new: "New",
  top_rated: "Highest",
  best_seller: "Best selling",
  beginner: "Starter level",
  intermediate: "Medium level",
  advanced: "Further level",
  free: "Free",
  paid: "Paid",
  promotion: "Promotion",
  certificate_of_completion: "Completion certificate",
  lifetime_access: "Lifetime access",
  learning_path: "Learning way",
  categories: "Categories",
  marketing: "Marketing",
  development: "Development",
  personal_development: "Personal development",
  finance: "Finance",
  recommended: "Proposed",
  trending_courses: "Trend courses",
  featured_courses: "Prominent courses",
  course_materials: "COURSE MATERIALS",
  resources: "Resources",
  downloads: "Downloaded",
  notes: "Notes",
  ask_instructor: "Ask the instructor",
  course_preview: "Course preview",
  course_description: "Course description",
  course_objectives: "Course targets",
  course_requirements: "Course requirements",
  student_reviews: "Student Comments",
  course_rating: "Course score",
  money_back_guarantee: "MONEY RETURN GUARANTEE",
  course_certificate: "Course certificate",
  lecture_notes: "Lecture notes",
  quizzes: "Tests",
  assignments: "Homework",
  coding_exercises: "Coding Exercises",
  real_world_projects: "Real world projects",
  on_demand_video: "Video on request",
  lifetime_learning: "Lifetime learning",
  discussion_board: "Discussion Panel",
  student_support: "Student support",
  mobile_learning: "Mobile learning",
  access_anytime: "Always access",
  multi_language_support: "Multilingual support"
};

export const enUK_with_quotes = {
  "hello": "Hello",
  "world": "World",
  "welcome": "Welcome to the world of i18n!",
  "goodbye": "Goodbye",
  "goodbye_message": "Goodbye, then see you!",
  "search": "Intermediate",
  "search_placeholder": "Search for something ...",
  "search_button": "Intermediate",
  "search_results": "Search results",
  "search_no_results": "Search results not found",
  "search_result": "Search result",
  "search_result_count": "Number of Search Results",
  "search_result_count_plural": "Number of Search Results",
  "search_result_count_0": "No search results",
  "computer": "Computer",
  "internet": "Internet",
  "language": "Language",
  "book": "Book",
  "school": "School",
  "teacher": "Teacher",
  "student": "Student",
  "university": "University",
  "science": "Science",
  "technology": "Technology",
  "engineering": "Engineering",
  "mathematics": "Maths",
  "medicine": "Medicine",
  "hospital": "Hospital",
  "doctor": "Doctor",
  "nurse": "Nurse",
  "health": "Health",
  "exercise": "Exercise",
  "sport": "Sport",
  "football": "Football",
  "basketball": "Basketball",
  "tennis": "Tennis",
  "music": "Music",
  "movie": "Film",
  "cinema": "Cinema",
  "actor": "Actor",
  "actress": "Actress",
  "director": "Director",
  "writer": "Writer",
  "novel": "Novel",
  "story": "Story",
  "news": "News",
  "journalism": "Journalism",
  "camera": "Camera",
  "photography": "Photography",
  "painting": "Picture",
  "art": "Art",
  "sculpture": "Statue",
  "architecture": "Architectural",
  "city": "City",
  "country": "Country",
  "village": "Bay",
  "ocean": "Ocean",
  "river": "River",
  "mountain": "Mountain",
  "forest": "Forest",
  "tree": "Tree",
  "flower": "Flower",
  "animal": "Animal",
  "bird": "Bird",
  "fish": "Fish",
  "dog": "Dog",
  "cat": "Cat",
  "car": "Car",
  "bicycle": "Bicycle",
  "train": "Train",
  "airplane": "Aeroplane",
  "travel": "Trip",
  "hotel": "Hotel",
  "restaurant": "Restaurant",
  "food": "Food",
  "water": "This",
  "coffee": "Coffee",
  "tea": "Tea",
  "bread": "Bread",
  "butter": "Butter",
  "cheese": "Cheese",
  "sugar": "Sugar",
  "salt": "Salt",
  "pepper": "Pepper",
  "fruit": "Fruit",
  "apple": "Apple",
  "banana": "Banana",
  "orange": "Orange",
  "grape": "Grape",
  "cherry": "Cherry",
  "strawberry": "Strawberry",
  "lemon": "Lemon",
  "vegetable": "Vegetable",
  "tomato": "Tomatoes",
  "potato": "Potatoes",
  "onion": "Onion",
  "garlic": "Garlic",
  "carrot": "Carrot",
  "cucumber": "Cucumber",
  "money": "Money",
  "bank": "Bank",
  "market": "Sunday",
  "shop": "Shopping centre",
  "store": "Shop",
  "price": "Price",
  "discount": "Discount",
  "sale": "Sales",
  "business": "Work",
  "company": "Company",
  "boss": "Boss",
  "manager": "Executive",
  "employee": "Worker",
  "meeting": "Meeting",
  "project": "Project",
  "contract": "Agreement",
  "agreement": "Agreement",
  "law": "Law",
  "judge": "Judge",
  "lawyer": "Lawyer",
  "court": "Court",
  "government": "Government",
  "politics": "Politics",
  "election": "Vote",
  "vote": "Vote",
  "citizen": "Citizen",
  "education": "Education",
  "teaching": "Teaching",
  "learning": "Learning",
  "knowledge": "Information",
  "wisdom": "Wisdom",
  "understanding": "Understanding",
  "college": "College",
  "professor": "Professor",
  "lecture": "Lesson",
  "classroom": "Class",
  "homework": "Homework",
  "assignment": "Duty",
  "exam": "Exam",
  "test": "Test",
  "grade": "Notes",
  "subject": "Course subject",
  "physics": "Physical",
  "chemistry": "Chemical",
  "biology": "Biology",
  "history": "History",
  "geography": "Geography",
  "literature": "Literature",
  "reading": "Reading",
  "writing": "Don't write",
  "speaking": "Speech",
  "listening": "Listening",
  "presentation": "Presentation",
  "discussion": "Argument",
  "debate": "Discussion",
  "notebook": "Notebook",
  "textbook": "Textbook",
  "library": "Library",
  "research": "Research",
  "experiment": "Experiment",
  "laboratory": "Lab",
  "curriculum": "Curriculum",
  "syllabus": "Course program",
  "lesson": "Lesson",
  "educator": "Instructor",
  "principal": "Manager",
  "dean": "Dean",
  "diploma": "Diploma",
  "degree": "Degree",
  "scholarship": "Scholarship",
  "tuition": "Tuition fee",
  "academic": "Academic",
  "graduate": "Graduate",
  "postgraduate": "Graduate",
  "undergraduate": "Licence",
  "certificate": "Certificate",
  "enrollment": "Record",
  "attendance": "Continue",
  "mentor": "Directory",
  "tutor": "Tutor",
  "coaching": "Coaching",
  "instruction": "Instructions",
  "self-study": "Self -work",
  "group-study": "Group work",
  "online-learning": "Learning online",
  "distance-learning": "Distance Learning",
  "e-learning": "E-learning",
  "virtual-classroom": "Virtual class",
  "interactive-learning": "Interactive learning",
  "critical-thinking": "Critical thinking",
  "problem-solving": "Solving problem",
  "collaboration": "Partnership",
  "communication": "Communication",
  "creativity": "Creativity",
  "innovation": "Innovation",
  "motivation": "Motivation",
  "inspiration": "Inspiration",
  "discipline": "Discipline",
  "time-management": "Time management",
  "goal-setting": "Targeting",
  "achievement": "Success",
  "evaluation": "Evaluation",
  "feedback": "Feedback",
  "revision": "Review",
  "memorization": "Memorizing",
  "analysis": "Analysis",
  "synthesis": "Synthetic",
  "comprehension": "Clutch",
  "interpretation": "Interpretation",
  "website": "Website",
  "homepage": "Home page",
  "about": "About",
  "contact": "Communication",
  "services": "Services",
  "products": "Products",
  "portfolio": "Portfolio",
  "blog": "Blog",
  "faq": "FAQ",
  "support": "Support",
  "privacy-policy": "Privacy Policy",
  "terms-of-service": "Service Terms",
  "login": "Entrance",
  "signup": "Register",
  "logout": "Make out",
  "profile": "Profile",
  "dashboard": "Control Panel",
  "settings": "Settings",
  "notifications": "Notifications",
  "filter": "Filter",
  "sort": "Ranking",
  "category": "Category",
  "subscribe": "Subscribe",
  "newsletter": "Bulletin",
  "download": "Download",
  "upload": "Install",
  "share": "Share",
  "like": "Like",
  "comment": "Comment",
  "review": "Examination",
  "rating": "Point",
  "terms": "Conditions",
  "conditions": "Conditions",
  "security": "Security",
  "cookies": "Cookies",
  "advertisement": "Advert",
  "sitemap": "Site Map",
  "help": "Help",
  "forum": "Forum",
  "community": "Community",
  "members": "Members",
  "admin": "Executive",
  "moderator": "Moderator",
  "user": "User",
  "visitor": "Visitor",
  "profile-picture": "Profile picture",
  "banner": "Banner",
  "header": "Upper information",
  "footer": "Sub -information",
  "menu": "Menu",
  "navigation": "Strolling",
  "button": "Button",
  "link": "Connection",
  "icon": "Symbol",
  "image": "Visual",
  "video": "Video",
  "audio": "Sound",
  "gallery": "Gallery",
  "media": "Media",
  "theme": "Theme",
  "template": "Template",
  "layout": "Order",
  "design": "Design",
  "content": "Contents",
  "text": "Text",
  "font": "Font",
  "color": "Colour",
  "background": "Background",
  "animation": "Animation",
  "effect": "Effect",
  "plugin": "Plug -in",
  "extension": "Extension",
  "database": "Database",
  "server": "Presenter",
  "hosting": "Hosting",
  "domain": "Domain name",
  "seo": "SEO",
  "analytics": "Analysis",
  "performance": "Performance",
  "optimization": "Optimization",
  "traffic": "Traffic",
  "conversion": "Transformation",
  "advertising": "Advertising",
  "social-media": "Social media",
  "campaign": "Offer",
  "ecommerce": "E-commerce",
  "cart": "Basket",
  "checkout": "Payment",
  "payment": "Payment",
  "invoice": "Invoice",
  "subscription": "Subscription",
  "membership": "Membership",
  "donation": "Donation",
  "customer": "Customer",
  "client": "Customer",
  "order": "Order",
  "tracking": "Follow-up",
  "delivery": "Delivery",
  "support-ticket": "Support ticket",
  "udemy": "Udemy",
  "course": "Course",
  "module": "Module",
  "section": "Section",
  "instructor": "Instructor",
  "enroll": "Signature",
  "completion": "Completion",
  "quiz": "Test",
  "transcript": "Transcript",
  "subtitles": "Subtitles",
  "notification": "Notification",
  "bookmark": "Location bookmark",
  "wishlist": "Request list",
  "popular": "Popular",
  "trending": "Trend",
  "new": "New",
  "top-rated": "Highest",
  "best-seller": "Best selling",
  "beginner": "Starter level",
  "intermediate": "Medium level",
  "advanced": "Further level",
  "free": "Free",
  "paid": "Paid",
  "promotion": "Promotion",
  "certificate-of-completion": "Completion certificate",
  "lifetime-access": "Lifetime access",
  "learning-path": "Learning way",
  "categories": "Categories",
  "marketing": "Marketing",
  "development": "Development",
  "personal-development": "Personal development",
  "finance": "Finance",
  "recommended": "Proposed",
  "trending-courses": "Trend courses",
  "featured-courses": "Prominent courses",
  "course-materials": "COURSE MATERIALS",
  "resources": "Resources",
  "downloads": "Downloaded",
  "notes": "Notes",
  "ask-instructor": "Ask the instructor",
  "course-preview": "Course preview",
  "course-description": "Course description",
  "course-objectives": "Course targets",
  "course-requirements": "Course requirements",
  "student-reviews": "Student Comments",
  "course-rating": "Course score",
  "money-back-guarantee": "MONEY RETURN GUARANTEE",
  "course-certificate": "Course certificate",
  "lecture-notes": "Lecture notes",
  "quizzes": "Tests",
  "assignments": "Homework",
  "coding-exercises": "Coding Exercises",
  "real-world-projects": "Real world projects",
  "on-demand-video": "Video on request",
  "lifetime-learning": "Lifetime learning",
  "discussion-board": "Discussion Panel",
  "student-support": "Student support",
  "mobile-learning": "Mobile learning",
  "access-anytime": "Always access",
  "multi-language-support": "Multilingual support"
}
