//src/app/assets/i18n/tr-TR.json.ts
export const trTR = {
  hello: "Merhaba",
  world: "Dünya",
  welcome: "i18n dünyasına hoş geldiniz!",
  goodbye: "Hoşça kal",
  goodbye_message: "Hoşça kal, sonra görüşürüz!",
  search: "Ara",
  search_placeholder: "Bir şeyler arayın...",
  search_button: "Ara",
  search_results: "Arama Sonuçları",
  search_no_results: "Arama sonuçları bulunamadı",
  search_result: "Arama Sonucu",
  search_result_count: "Arama Sonucu Sayısı",
  search_result_count_plural: "Arama Sonucu Sayısı",
  search_result_count_0: "Arama Sonucu Yok",
  computer: "Bilgisayar",
  internet: "İnternet",
  language: "Dil",
  book: "Kitap",
  school: "Okul",
  teacher: "Öğretmen",
  student: "Öğrenci",
  university: "Üniversite",
  science: "Bilim",
  technology: "Teknoloji",
  engineering: "Mühendislik",
  mathematics: "Matematik",
  medicine: "Tıp",
  hospital: "Hastane",
  doctor: "Doktor",
  nurse: "Hemşire",
  health: "Sağlık",
  exercise: "Egzersiz",
  sport: "Spor",
  football: "Futbol",
  basketball: "Basketbol",
  tennis: "Tenis",
  music: "Müzik",
  movie: "Film",
  cinema: "Sinema",
  actor: "Oyuncu",
  actress: "Kadın Oyuncu",
  director: "Yönetmen",
  writer: "Yazar",
  novel: "Roman",
  story: "Hikaye",
  news: "Haber",
  journalism: "Gazetecilik",
  camera: "Kamera",
  photography: "Fotoğrafçılık",
  painting: "Resim",
  art: "Sanat",
  sculpture: "Heykel",
  architecture: "Mimari",
  city: "Şehir",
  country: "Ülke",
  village: "Köy",
  ocean: "Okyanus",
  river: "Nehir",
  mountain: "Dağ",
  forest: "Orman",
  tree: "Ağaç",
  flower: "Çiçek",
  animal: "Hayvan",
  bird: "Kuş",
  fish: "Balık",
  dog: "Köpek",
  cat: "Kedi",
  car: "Araba",
  bicycle: "Bisiklet",
  train: "Tren",
  airplane: "Uçak",
  travel: "Seyahat",
  hotel: "Otel",
  restaurant: "Restoran",
  food: "Yemek",
  water: "Su",
  coffee: "Kahve",
  tea: "Çay",
  bread: "Ekmek",
  butter: "Tereyağı",
  cheese: "Peynir",
  sugar: "Şeker",
  salt: "Tuz",
  pepper: "Biber",
  fruit: "Meyve",
  apple: "Elma",
  banana: "Muz",
  orange: "Portakal",
  grape: "Üzüm",
  cherry: "Kiraz",
  strawberry: "Çilek",
  lemon: "Limon",
  vegetable: "Sebze",
  tomato: "Domates",
  potato: "Patates",
  onion: "Soğan",
  garlic: "Sarmısak",
  carrot: "Havuç",
  cucumber: "Salatalık",
  money: "Para",
  bank: "Banka",
  market: "Pazar",
  shop: "Mağaza",
  store: "Dükkan",
  price: "Fiyat",
  discount: "İndirim",
  sale: "Satış",
  business: "İş",
  company: "Şirket",
  boss: "Patron",
  manager: "Yönetici",
  employee: "Çalışan",
  meeting: "Toplantı",
  project: "Proje",
  contract: "Sözleşme",
  agreement: "Anlaşma",
  law: "Hukuk",
  judge: "Hakim",
  lawyer: "Avukat",
  court: "Mahkeme",
  government: "Hükümet",
  politics: "Siyaset",
  election: "Seçim",
  vote: "Oy",
  citizen: "Vatandaş",
  education: "Eğitim",
  teaching: "Öğretim",
  learning: "Öğrenme",
  knowledge: "Bilgi",
  wisdom: "Bilgelik",
  understanding: "Anlama",
  college: "Kolej",
  professor: "Profesör",
  lecture: "Ders",
  classroom: "Sınıf",
  homework: "Ödev",
  assignment: "Görev",
  exam: "Sınav",
  test: "Test",
  grade: "Not",
  subject: "Ders Konusu",
  physics: "Fizik",
  chemistry: "Kimya",
  biology: "Biyoloji",
  history: "Tarih",
  geography: "Coğrafya",
  literature: "Edebiyat",
  reading: "Okuma",
  writing: "Yazma",
  speaking: "Konuşma",
  listening: "Dinleme",
  presentation: "Sunum",
  discussion: "Tartışma",
  debate: "Munazara",
  notebook: "Defter",
  textbook: "Ders Kitabı",
  library: "Kütüphane",
  research: "Araştırma",
  experiment: "Deney",
  laboratory: "Laboratuvar",
  curriculum: "Müfredat",
  syllabus: "Ders Programı",
  lesson: "Ders",
  educator: "Eğitmen",
  principal: "Müdür",
  dean: "Dekan",
  diploma: "Diploma",
  degree: "Derece",
  scholarship: "Burs",
  tuition: "Öğrenim Ücreti",
  academic: "Akademik",
  graduate: "Mezun",
  postgraduate: "Lisans üstü",
  undergraduate: "Lisans",
  certificate: "Sertifika",
  enrollment: "Kayıt",
  attendance: "Devam",
  mentor: "Rehber",
  tutor: "Özel öğretmen",
  coaching: "Koçluk",
  instruction: "Talimat",
  self_study: "Kendi kendine çalışma",
  group_study: "Grup çalışması",
  online_learning: "Çevrimiçi öğrenme",
  distance_learning: "Uzaktan eğitim",
  e_learning: "E_öğrenme",
  virtual_classroom: "Sanal sınıf",
  interactive_learning: "Etkileşimli öğrenme",
  critical_thinking: "Eleştirisel düşünme",
  problem_solving: "Problemi çözme",
  collaboration: "İşbirliği",
  communication: "İletişim",
  creativity: "Yaratıcılık",
  innovation: "İnovasyon",
  motivation: "Motivasyon",
  inspiration: "İlham",
  discipline: "Disiplin",
  time_management: "Zaman yönetimi",
  goal_setting: "Hedef belirleme",
  achievement: "Başarı",
  evaluation: "Değerlendirme",
  feedback: "Geri bildirim",
  revision: "Gözden geçirme",
  memorization: "Ezberleme",
  analysis: "Analiz",
  synthesis: "Sentetik",
  comprehension: "Kavrama",
  interpretation: "Yorumlama",
  website: "Web sitesi",
  homepage: "Ana sayfa",
  about: "Hakkında",
  contact: "İletişim",
  services: "Hizmetler",
  products: "Ürünler",
  portfolio: "Portföy",
  blog: "Blog",
  faq: "SSS",
  support: "Destek",
  privacy_policy: "Gizlilik politikası",
  terms_of_service: "Hizmet şartları",
  login: "Giriş",
  signup: "Kayıt ol",
  logout: "Çıkış yap",
  profile: "Profil",
  dashboard: "Kontrol paneli",
  settings: "Ayarlar",
  notifications: "Bildirimler",
  filter: "Filtre",
  sort: "Sırala",
  category: "Kategori",
  subscribe: "Abone ol",
  newsletter: "Bülten",
  download: "İndir",
  upload: "Yükle",
  share: "Paylaş",
  like: "Beğen",
  comment: "Yorum",
  review: "İnceleme",
  rating: "Puan",
  terms: "Şartlar",
  conditions: "Koşullar",
  security: "Güvenlik",
  cookies: "Çerezler",
  advertisement: "Reklam",
  sitemap: "Site haritası",
  help: "Yardım",
  forum: "Forum",
  community: "Topluluk",
  members: "Üyeler",
  admin: "Yönetici",
  moderator: "Moderatör",
  user: "Kullanıcı",
  visitor: "Ziyaretçi",
  profile_picture: "Profil resmi",
  banner: "Afiş",
  header: "Üst bilgi",
  footer: "Alt bilgi",
  menu: "Menü",
  navigation: "Gezinme",
  button: "Düğme",
  link: "Bağlantı",
  icon: "Simge",
  image: "Görsel",
  video: "Video",
  audio: "Ses",
  gallery: "Galeri",
  media: "Medya",
  theme: "Tema",
  template: "Şablon",
  layout: "Düzen",
  design: "Tasarım",
  content: "İçerik",
  text: "Metin",
  font: "Yazı tipi",
  color: "Renk",
  background: "Arka plan",
  animation: "Animasyon",
  effect: "Efekt",
  plugin: "Eklenti",
  extension: "Uzantı",
  database: "Veritabanı",
  server: "Sunucu",
  hosting: "Barındırma",
  domain: "Alan adı",
  seo: "SEO",
  analytics: "Analiz",
  performance: "Performans",
  optimization: "Optimizasyon",
  traffic: "Trafik",
  conversion: "Dönüşüm",
  advertising: "Reklamcılık",
  social_media: "Sosyal medya",
  campaign: "Kampanya",
  ecommerce: "E_ticaret",
  cart: "Sepet",
  checkout: "Ödeme",
  payment: "Ödeme",
  invoice: "Fatura",
  subscription: "Abonelik",
  membership: "Üyelik",
  donation: "Bağış",
  customer: "Müşteri",
  client: "Müşteri",
  order: "Sipariş",
  tracking: "Takip",
  delivery: "Teslimat",
  support_ticket: "Destek bileti",
  udemy: "Udemy",
  course: "Kurs",
  module: "Modül",
  section: "Bölüm",
  instructor: "Eğitmen",
  enroll: "Kaydol",
  completion: "Tamamlama",
  quiz: "Test",
  transcript: "Transkript",
  subtitles: "Altyazılar",
  notification: "Bildirim",
  bookmark: "Yer imi",
  wishlist: "İstek listesi",
  popular: "Popüler",
  trending: "Trend",
  new: "Yeni",
  top_rated: "En yüksek puanlı",
  best_seller: "En çok satan",
  beginner: "Başlangıç seviyesi",
  intermediate: "Orta seviye",
  advanced: "İleri seviye",
  free: "Ücretsiz",
  paid: "Ücretli",
  promotion: "Promosyon",
  certificate_of_completion: "Tamamlama sertifikası",
  lifetime_access: "Ömür boyu erişim",
  learning_path: "Öğrenme yolu",
  categories: "Kategoriler",
  marketing: "Pazarlama",
  development: "Geliştirme",
  personal_development: "Kişisel gelişim",
  finance: "Finans",
  recommended: "Önerilen",
  trending_courses: "Trend kurslar",
  featured_courses: "Öne çıkan kurslar",
  course_materials: "Kurs materyalleri",
  resources: "Kaynaklar",
  downloads: "İndirilenler",
  notes: "Notlar",
  ask_instructor: "Eğitmene sor",
  course_preview: "Kurs önizleme",
  course_description: "Kurs açıklaması",
  course_objectives: "Kurs hedefleri",
  course_requirements: "Kurs gereksinimleri",
  student_reviews: "Öğrenci yorumları",
  course_rating: "Kurs puanı",
  money_back_guarantee: "Para iade garantisi",
  course_certificate: "Kurs sertifikası",
  lecture_notes: "Ders notları",
  quizzes: "Testler",
  assignments: "Ödevler",
  coding_exercises: "Kodlama alıştırmaları",
  real_world_projects: "Gerçek dünya projeleri",
  on_demand_video: "Talep üzerine video",
  lifetime_learning: "Ömür boyu öğrenme",
  discussion_board: "Tartışma panosu",
  student_support: "Öğrenci desteği",
  mobile_learning: "Mobil öğrenme",
  access_anytime: "Her zaman erişim",
  multi_language_support: "Çok dilli destek"
};

export const trTR_with_quotes = {
  "hello": "Merhaba",
  "world": "Dünya",
  "welcome": "i18n dünyasına hoş geldiniz!",
  "goodbye": "Hoşça kal",
  "goodbye_message": "Hoşça kal, sonra görüşürüz!",
  "search": "Ara",
  "search_placeholder": "Bir şeyler arayın...",
  "search_button": "Ara",
  "search_results": "Arama Sonuçları",
  "search_no_results": "Arama sonuçları bulunamadı",
  "search_result": "Arama Sonucu",
  "search_result_count": "Arama Sonucu Sayısı",
  "search_result_count_plural": "Arama Sonucu Sayısı",
  "search_result_count_0": "Arama Sonucu Yok",
  "computer": "Bilgisayar",
  "internet": "İnternet",
  "language": "Dil",
  "book": "Kitap",
  "school": "Okul",
  "teacher": "Öğretmen",
  "student": "Öğrenci",
  "university": "Üniversite",
  "science": "Bilim",
  "technology": "Teknoloji",
  "engineering": "Mühendislik",
  "mathematics": "Matematik",
  "medicine": "Tıp",
  "hospital": "Hastane",
  "doctor": "Doktor",
  "nurse": "Hemşire",
  "health": "Sağlık",
  "exercise": "Egzersiz",
  "sport": "Spor",
  "football": "Futbol",
  "basketball": "Basketbol",
  "tennis": "Tenis",
  "music": "Müzik",
  "movie": "Film",
  "cinema": "Sinema",
  "actor": "Oyuncu",
  "actress": "Kadın Oyuncu",
  "director": "Yönetmen",
  "writer": "Yazar",
  "novel": "Roman",
  "story": "Hikaye",
  "news": "Haber",
  "journalism": "Gazetecilik",
  "camera": "Kamera",
  "photography": "Fotoğrafçılık",
  "painting": "Resim",
  "art": "Sanat",
  "sculpture": "Heykel",
  "architecture": "Mimari",
  "city": "Şehir",
  "country": "Ülke",
  "village": "Köy",
  "ocean": "Okyanus",
  "river": "Nehir",
  "mountain": "Dağ",
  "forest": "Orman",
  "tree": "Ağaç",
  "flower": "Çiçek",
  "animal": "Hayvan",
  "bird": "Kuş",
  "fish": "Balık",
  "dog": "Köpek",
  "cat": "Kedi",
  "car": "Araba",
  "bicycle": "Bisiklet",
  "train": "Tren",
  "airplane": "Uçak",
  "travel": "Seyahat",
  "hotel": "Otel",
  "restaurant": "Restoran",
  "food": "Yemek",
  "water": "Su",
  "coffee": "Kahve",
  "tea": "Çay",
  "bread": "Ekmek",
  "butter": "Tereyağı",
  "cheese": "Peynir",
  "sugar": "Şeker",
  "salt": "Tuz",
  "pepper": "Biber",
  "fruit": "Meyve",
  "apple": "Elma",
  "banana": "Muz",
  "orange": "Portakal",
  "grape": "Üzüm",
  "cherry": "Kiraz",
  "strawberry": "Çilek",
  "lemon": "Limon",
  "vegetable": "Sebze",
  "tomato": "Domates",
  "potato": "Patates",
  "onion": "Soğan",
  "garlic": "Sarmısak",
  "carrot": "Havuç",
  "cucumber": "Salatalık",
  "money": "Para",
  "bank": "Banka",
  "market": "Pazar",
  "shop": "Mağaza",
  "store": "Dükkan",
  "price": "Fiyat",
  "discount": "İndirim",
  "sale": "Satış",
  "business": "İş",
  "company": "Şirket",
  "boss": "Patron",
  "manager": "Yönetici",
  "employee": "Çalışan",
  "meeting": "Toplantı",
  "project": "Proje",
  "contract": "Sözleşme",
  "agreement": "Anlaşma",
  "law": "Hukuk",
  "judge": "Hakim",
  "lawyer": "Avukat",
  "court": "Mahkeme",
  "government": "Hükümet",
  "politics": "Siyaset",
  "election": "Seçim",
  "vote": "Oy",
  "citizen": "Vatandaş",
  "education": "Eğitim",
  "teaching": "Öğretim",
  "learning": "Öğrenme",
  "knowledge": "Bilgi",
  "wisdom": "Bilgelik",
  "understanding": "Anlama",
  "college": "Kolej",
  "professor": "Profesör",
  "lecture": "Ders",
  "classroom": "Sınıf",
  "homework": "Ödev",
  "assignment": "Görev",
  "exam": "Sınav",
  "test": "Test",
  "grade": "Not",
  "subject": "Ders Konusu",
  "physics": "Fizik",
  "chemistry": "Kimya",
  "biology": "Biyoloji",
  "history": "Tarih",
  "geography": "Coğrafya",
  "literature": "Edebiyat",
  "reading": "Okuma",
  "writing": "Yazma",
  "speaking": "Konuşma",
  "listening": "Dinleme",
  "presentation": "Sunum",
  "discussion": "Tartışma",
  "debate": "Munazara",
  "notebook": "Defter",
  "textbook": "Ders Kitabı",
  "library": "Kütüphane",
  "research": "Araştırma",
  "experiment": "Deney",
  "laboratory": "Laboratuvar",
  "curriculum": "Müfredat",
  "syllabus": "Ders Programı",
  "lesson": "Ders",
  "educator": "Eğitmen",
  "principal": "Müdür",
  "dean": "Dekan",
  "diploma": "Diploma",
  "degree": "Derece",
  "scholarship": "Burs",
  "tuition": "Öğrenim Ücreti",
  "academic": "Akademik",
  "graduate": "Mezun",
  "postgraduate": "Lisans üstü",
  "undergraduate": "Lisans",
  "certificate": "Sertifika",
  "enrollment": "Kayıt",
  "attendance": "Devam",
  "mentor": "Rehber",
  "tutor": "Özel öğretmen",
  "coaching": "Koçluk",
  "instruction": "Talimat",
  "self-study": "Kendi kendine çalışma",
  "group-study": "Grup çalışması",
  "online-learning": "Çevrimiçi öğrenme",
  "distance-learning": "Uzaktan eğitim",
  "e-learning": "E-öğrenme",
  "virtual-classroom": "Sanal sınıf",
  "interactive-learning": "Etkileşimli öğrenme",
  "critical-thinking": "Eleştirisel düşünme",
  "problem-solving": "Problemi çözme",
  "collaboration": "İşbirliği",
  "communication": "İletişim",
  "creativity": "Yaratıcılık",
  "innovation": "İnovasyon",
  "motivation": "Motivasyon",
  "inspiration": "İlham",
  "discipline": "Disiplin",
  "time-management": "Zaman yönetimi",
  "goal-setting": "Hedef belirleme",
  "achievement": "Başarı",
  "evaluation": "Değerlendirme",
  "feedback": "Geri bildirim",
  "revision": "Gözden geçirme",
  "memorization": "Ezberleme",
  "analysis": "Analiz",
  "synthesis": "Sentetik",
  "comprehension": "Kavrama",
  "interpretation": "Yorumlama",
  "website": "Web sitesi",
  "homepage": "Ana sayfa",
  "about": "Hakkında",
  "contact": "İletişim",
  "services": "Hizmetler",
  "products": "Ürünler",
  "portfolio": "Portföy",
  "blog": "Blog",
  "faq": "SSS",
  "support": "Destek",
  "privacy-policy": "Gizlilik politikası",
  "terms-of-service": "Hizmet şartları",
  "login": "Giriş",
  "signup": "Kayıt ol",
  "logout": "Çıkış yap",
  "profile": "Profil",
  "dashboard": "Kontrol paneli",
  "settings": "Ayarlar",
  "notifications": "Bildirimler",
  "filter": "Filtre",
  "sort": "Sırala",
  "category": "Kategori",
  "subscribe": "Abone ol",
  "newsletter": "Bülten",
  "download": "İndir",
  "upload": "Yükle",
  "share": "Paylaş",
  "like": "Beğen",
  "comment": "Yorum",
  "review": "İnceleme",
  "rating": "Puan",
  "terms": "Şartlar",
  "conditions": "Koşullar",
  "security": "Güvenlik",
  "cookies": "Çerezler",
  "advertisement": "Reklam",
  "sitemap": "Site haritası",
  "help": "Yardım",
  "forum": "Forum",
  "community": "Topluluk",
  "members": "Üyeler",
  "admin": "Yönetici",
  "moderator": "Moderatör",
  "user": "Kullanıcı",
  "visitor": "Ziyaretçi",
  "profile-picture": "Profil resmi",
  "banner": "Afiş",
  "header": "Üst bilgi",
  "footer": "Alt bilgi",
  "menu": "Menü",
  "navigation": "Gezinme",
  "button": "Düğme",
  "link": "Bağlantı",
  "icon": "Simge",
  "image": "Görsel",
  "video": "Video",
  "audio": "Ses",
  "gallery": "Galeri",
  "media": "Medya",
  "theme": "Tema",
  "template": "Şablon",
  "layout": "Düzen",
  "design": "Tasarım",
  "content": "İçerik",
  "text": "Metin",
  "font": "Yazı tipi",
  "color": "Renk",
  "background": "Arka plan",
  "animation": "Animasyon",
  "effect": "Efekt",
  "plugin": "Eklenti",
  "extension": "Uzantı",
  "database": "Veritabanı",
  "server": "Sunucu",
  "hosting": "Barındırma",
  "domain": "Alan adı",
  "seo": "SEO",
  "analytics": "Analiz",
  "performance": "Performans",
  "optimization": "Optimizasyon",
  "traffic": "Trafik",
  "conversion": "Dönüşüm",
  "advertising": "Reklamcılık",
  "social-media": "Sosyal medya",
  "campaign": "Kampanya",
  "ecommerce": "E-ticaret",
  "cart": "Sepet",
  "checkout": "Ödeme",
  "payment": "Ödeme",
  "invoice": "Fatura",
  "subscription": "Abonelik",
  "membership": "Üyelik",
  "donation": "Bağış",
  "customer": "Müşteri",
  "client": "Müşteri",
  "order": "Sipariş",
  "tracking": "Takip",
  "delivery": "Teslimat",
  "support-ticket": "Destek bileti",
  "udemy": "Udemy",
  "course": "Kurs",
  "module": "Modül",
  "section": "Bölüm",
  "instructor": "Eğitmen",
  "enroll": "Kaydol",
  "completion": "Tamamlama",
  "quiz": "Test",
  "transcript": "Transkript",
  "subtitles": "Altyazılar",
  "notification": "Bildirim",
  "bookmark": "Yer imi",
  "wishlist": "İstek listesi",
  "popular": "Popüler",
  "trending": "Trend",
  "new": "Yeni",
  "top-rated": "En yüksek puanlı",
  "best-seller": "En çok satan",
  "beginner": "Başlangıç seviyesi",
  "intermediate": "Orta seviye",
  "advanced": "İleri seviye",
  "free": "Ücretsiz",
  "paid": "Ücretli",
  "promotion": "Promosyon",
  "certificate-of-completion": "Tamamlama sertifikası",
  "lifetime-access": "Ömür boyu erişim",
  "learning-path": "Öğrenme yolu",
  "categories": "Kategoriler",
  "marketing": "Pazarlama",
  "development": "Geliştirme",
  "personal-development": "Kişisel gelişim",
  "finance": "Finans",
  "recommended": "Önerilen",
  "trending-courses": "Trend kurslar",
  "featured-courses": "Öne çıkan kurslar",
  "course-materials": "Kurs materyalleri",
  "resources": "Kaynaklar",
  "downloads": "İndirilenler",
  "notes": "Notlar",
  "ask-instructor": "Eğitmene sor",
  "course-preview": "Kurs önizleme",
  "course-description": "Kurs açıklaması",
  "course-objectives": "Kurs hedefleri",
  "course-requirements": "Kurs gereksinimleri",
  "student-reviews": "Öğrenci yorumları",
  "course-rating": "Kurs puanı",
  "money-back-guarantee": "Para iade garantisi",
  "course-certificate": "Kurs sertifikası",
  "lecture-notes": "Ders notları",
  "quizzes": "Testler",
  "assignments": "Ödevler",
  "coding-exercises": "Kodlama alıştırmaları",
  "real-world-projects": "Gerçek dünya projeleri",
  "on-demand-video": "Talep üzerine video",
  "lifetime-learning": "Ömür boyu öğrenme",
  "discussion-board": "Tartışma panosu",
  "student-support": "Öğrenci desteği",
  "mobile-learning": "Mobil öğrenme",
  "access-anytime": "Her zaman erişim",
  "multi-language-support": "Çok dilli destek"
};
